import { LightningElement } from 'lwc';
import { USER_DETAILS, SOCIAL_LINKS, PROFILE_IMAGE, CAREER_SUMMARY, EXPERIENCE_DATA, EDUCATION_DATA, CERTIFICATION_DATA, SKILLS_DATA, INTERESTS_DATA } from './myResumeContainerData';

export default class MyResumeContainer extends LightningElement {
    // Assign the imported value to a property
    USER_DETAILS = USER_DETAILS;
    SOCIAL_LINKS = SOCIAL_LINKS;
    PROFILE_IMAGE = PROFILE_IMAGE;
    CAREER_SUMMARY = CAREER_SUMMARY;
    EXPERIENCE_DATA = EXPERIENCE_DATA;
    EDUCATION_DATA = EDUCATION_DATA;
    CERTIFICATION_DATA = CERTIFICATION_DATA;
    SKILLS_DATA = SKILLS_DATA;
    INTERESTS_DATA = INTERESTS_DATA;
}